blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: "âœ¨ Feature"
    description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€"
    file: feature.yml
  - name: "ğŸ› Bug"
    description: "ë²„ê·¸ ë¦¬í¬íŠ¸"
    file: bug.yml
